#!/usr/bin/env python3
# @ai-generated
"""
Generates verseUnitsFixture.json for services/mushaf/__tests__/RewayahVerseUnits.test.ts.

The fixture holds the real slots (id, Hafs location, text) of a few COMPLETE
surahs in several Release 1 words DBs, and the verse units EXPECTED from them,
computed here independently of the TypeScript builder:

  per surah, slots in id order; a unit ends at a slot whose last token is a
  verse marker ('۝N': a Hafs marker slot holding the rewayah's number, or an
  inline marker at the end of a content slot); blank slots belong to the unit
  being walked; when no slot of Hafs 1:1 ends a verse (Madani / Basri counts)
  the Hafs 1:1 slots are the unnumbered Fatiha basmala and belong to no unit.

  unit = [surah, ayah, firstWordId, lastWordId, hafsKeys, anchorKey, text]
    hafsKeys  = Hafs verse keys of the slots holding the unit's words
    anchorKey = "S:A" when the unit starts at Hafs word 1 and is the only
                unit holding words of Hafs verse S:A, else "S:A:W" (the
                first part of a split Hafs verse is "S:A:1")
    text      = the unit's non-blank slot texts joined by single spaces

Surahs (short ones that still exercise every case): 1 (Madani / Basri:
unnumbered basmala and the split Hafs 1:7), 71 (al-Bazzi / al-Duri: verses
that hold the end of one Hafs verse and the start of the next), 103 (Warsh:
split and merge), 106 and 112 and 114 (splits), 107 (merge).

Usage (inputs are read-only; the Release 1 DBs come from the data branch):
  python3 -I gen_verse_units_fixture.py --db-dir <dir with digital-khatt-v2.db
      and dk_words_<id>.db> --out verseUnitsFixture.json
"""
from __future__ import annotations

import argparse
import json
import re
import sqlite3
from pathlib import Path

SURAHS = [1, 71, 103, 106, 107, 112, 114]
DBS = {
    "hafs": "digital-khatt-v2.db",
    "shouba": "dk_words_shouba.db",
    "warsh": "dk_words_warsh.db",
    "bazzi": "dk_words_bazzi.db",
    "doori": "dk_words_doori.db",
}
MARKER = re.compile(r"^\u06DD([\u0660-\u0669]+)$")


def marker_number(token: str) -> int | None:
    m = MARKER.match(token)
    if not m:
        return None
    return int("".join(str(ord(c) - 0x0660) for c in m.group(1)))


def read(db_path: Path) -> list[tuple[int, int, int, int, str]]:
    con = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    try:
        marks = ",".join("?" * len(SURAHS))
        return con.execute(
            f"SELECT id, surah, ayah, word, text FROM words WHERE surah IN ({marks}) ORDER BY id",
            SURAHS,
        ).fetchall()
    finally:
        con.close()


def expected_units(rows):
    units, unnumbered = [], []
    for surah in SURAHS:
        srows = [r for r in rows if r[1] == surah]
        k = 0
        if surah == 1 and not any(
            r[2] == 1 and r[4] and marker_number(r[4].split(" ")[-1]) is not None for r in srows
        ):
            while srows[k][2] == 1:
                k += 1
            unnumbered.append([srows[0][0], srows[k - 1][0]])
        start, hafs_keys, texts = None, [], []
        for wid, s, a, w, text in srows[k:]:
            if start is None:
                start = (wid, a, w)
            if not text:
                continue
            texts.append(text)
            toks = text.split(" ")
            if any(marker_number(t) is None for t in toks):
                key = f"{s}:{a}"
                if not hafs_keys or hafs_keys[-1] != key:
                    hafs_keys.append(key)
            n = marker_number(toks[-1])
            if n is None:
                continue
            fid, fa, fw = start
            units.append([surah, n, fid, wid, hafs_keys, (fa, fw), " ".join(texts)])
            start, hafs_keys, texts = None, [], []
        assert start is None, f"surah {surah} ends inside a verse"
    # Anchor keys need every unit: a bare "S:A" only for the one unit
    # holding words of Hafs verse S:A.
    holders: dict[str, int] = {}
    for unit in units:
        for key in unit[4]:
            holders[key] = holders.get(key, 0) + 1
    for unit in units:
        fa, fw = unit[5]
        key = f"{unit[0]}:{fa}"
        alone = fw == 1 and unit[4][:1] == [key] and holders[key] == 1
        unit[5] = key if alone else f"{key}:{fw}"
    return units, unnumbered


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--db-dir", type=Path, required=True)
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args()

    rows_by_db = {db: read(args.db_dir / name) for db, name in DBS.items()}
    hafs = rows_by_db["hafs"]
    for db, rows in rows_by_db.items():
        assert [r[:4] for r in rows] == [r[:4] for r in hafs], f"{db}: rows differ from Hafs"

    out = {
        "about": "Real slots of complete surahs from the Release 1 words DBs; "
        "generated by gen_verse_units_fixture.py",
        "surahs": SURAHS,
        "ids": [r[0] for r in hafs],
        "locations": [f"{r[1]}:{r[2]}:{r[3]}" for r in hafs],
        "texts": {db: [r[4] for r in rows] for db, rows in rows_by_db.items()},
        "expected": {},
        "unnumbered": {},
    }
    for db, rows in rows_by_db.items():
        units, unnumbered = expected_units(rows)
        out["expected"][db] = units
        out["unnumbered"][db] = unnumbered
    args.out.write_text(json.dumps(out, ensure_ascii=False, separators=(",", ":")) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
