/**
 * Test-only loader for rewayahOverlayFixture.json (generated by
 * gen_rewayah_overlay_fixture.py from real words DBs and the shared layout DB)
 * plus a fixture-backed stand-in for DigitalKhattDataService's read API.
 *
 * Not imported by app code.
 */
import type {DKLine, DKWordInfo} from '../DigitalKhattDataService';
import type {RewayahId} from '@/services/rewayah/RewayahIdentity';
import type {IndexedTajweedData} from '@/utils/tajweedLoader';
import {joinSlotTexts, layoutLineSlots, visibleWords} from '../lineWordSpans';

/** Words DBs in the fixture (file ids; 'hafs' is digital-khatt-v2.db). */
export type FixtureDb =
  | 'hafs'
  | 'shouba'
  | 'warsh'
  | 'qaloon'
  | 'bazzi'
  | 'qumbul'
  | 'doori'
  | 'soosi';

export const FIXTURE_DBS: readonly FixtureDb[] = [
  'hafs',
  'shouba',
  'warsh',
  'qaloon',
  'bazzi',
  'qumbul',
  'doori',
  'soosi',
];

/** App RewayahId for each fixture DB. */
export const FIXTURE_DB_REWAYAH: Record<FixtureDb, RewayahId> = {
  hafs: 'hafs',
  shouba: 'shubah',
  warsh: 'warsh',
  qaloon: 'qalun',
  bazzi: 'al-bazzi',
  qumbul: 'qunbul',
  doori: 'al-duri-abi-amr',
  soosi: 'al-susi',
};

export interface ExpectedLine {
  lineIndex: number;
  textLength: number;
  /** Flattened [wordId, start, wordEnd] triples, one per non-blank slot. */
  spans: number[];
  /** [verseKey, start, end, firstWordId, lastWordId] */
  segments: [string, number, number, number, number][];
}

export interface FixturePage {
  page: number;
  firstWordId: number;
  lastWordId: number;
  /** [line_number, line_type, is_centered, first_word_id, last_word_id, surah_number] */
  lines: [
    number,
    DKLine['line_type'],
    0 | 1,
    number | '',
    number | '',
    number | '',
  ][];
  locations: string[];
  texts: Record<FixtureDb, string[]>;
  expected: Record<FixtureDb, ExpectedLine[]>;
}

export type DiffFile = Record<string, unknown>;

export interface RewayahOverlayFixture {
  pages: FixturePage[];
  tajweed: IndexedTajweedData;
  diffs: {
    legacy: Record<'warsh' | 'bazzi', DiffFile>;
    format2: Record<'warsh' | 'bazzi' | 'soosi', DiffFile>;
  };
}

export const fixture =
  require('./rewayahOverlayFixture.json') as RewayahOverlayFixture;

export function pageLines(page: FixturePage): DKLine[] {
  return page.lines.map(
    ([lineNumber, lineType, isCentered, first, last, surah]) => ({
      page_number: page.page,
      line_number: lineNumber,
      line_type: lineType,
      is_centered: isCentered,
      first_word_id: first as number,
      last_word_id: last as number,
      surah_number: surah as number,
    }),
  );
}

export function slotText(
  page: FixturePage,
  db: FixtureDb,
  wordId: number,
): string {
  return page.texts[db][wordId - page.firstWordId];
}

/** Expected spans of a line as {wordId, start, end, wordEnd}. */
export function expectedSpans(
  page: FixturePage,
  db: FixtureDb,
  line: ExpectedLine,
): {wordId: number; start: number; end: number; wordEnd: number}[] {
  const out = [];
  for (let i = 0; i < line.spans.length; i += 3) {
    const wordId = line.spans[i];
    const start = line.spans[i + 1];
    out.push({
      wordId,
      start,
      end: start + slotText(page, db, wordId).length - 1,
      wordEnd: line.spans[i + 2],
    });
  }
  return out;
}

export function findPage(pageNumber: number): FixturePage {
  const page = fixture.pages.find(p => p.page === pageNumber);
  if (!page) throw new Error(`page ${pageNumber} is not in the fixture`);
  return page;
}

/**
 * Fixture-backed stand-in for the DigitalKhattDataService read API used by
 * the overlay services. Its text joins are the same lineWordSpans helpers the
 * real service delegates to. `load` swaps the active words (like a rewayah
 * switch) and bumps the cache version; `bumpVersion` simulates a data reload.
 */
export interface FakeDKService {
  readonly rewayah: RewayahId;
  readonly initialized: boolean;
  getCacheVersion(): number;
  subscribeCacheChanges(listener: () => void): () => void;
  getPageLines(pageNumber: number): DKLine[];
  getWordText(wordId: number): string;
  getWordInfo(wordId: number): DKWordInfo | undefined;
  getLineText(line: DKLine): string;
  getVerseWords(verseKey: string, rewayah?: RewayahId): DKWordInfo[];
  getVerseText(verseKey: string, rewayah?: RewayahId): string;
  load(db: FixtureDb): void;
  /** Loads arbitrary words ([id, 'surah:ayah:word', text]) and layout lines. */
  loadData(data: {
    rewayah: RewayahId;
    words: [number, string, string][];
    lines: DKLine[];
  }): void;
  bumpVersion(): void;
}

const noop = (): void => undefined;

export function createFakeDKService(basmallahText: string): FakeDKService {
  let rewayah: RewayahId = 'hafs';
  let version = 0;
  const wordsById = new Map<number, string>();
  const infoById = new Map<number, DKWordInfo>();
  const verseWords = new Map<string, DKWordInfo[]>();
  const lines = new Map<number, DKLine[]>();

  return {
    get rewayah() {
      return rewayah;
    },
    get initialized() {
      return true;
    },
    getCacheVersion: () => version,
    subscribeCacheChanges: () => noop,
    getPageLines: pageNumber => lines.get(pageNumber) ?? [],
    getWordText: wordId => wordsById.get(wordId) || '',
    getWordInfo: wordId => infoById.get(wordId),
    getLineText(line) {
      if (line.line_type === 'surah_name') return '';
      if (line.line_type === 'basmallah') return basmallahText;
      return layoutLineSlots(line.first_word_id, line.last_word_id, id =>
        this.getWordText(id),
      ).text;
    },
    getVerseWords(verseKey, requested) {
      if (requested && requested !== rewayah) return [];
      const slots = verseWords.get(verseKey);
      return slots ? visibleWords(slots) : [];
    },
    getVerseText(verseKey, requested) {
      return joinSlotTexts(this.getVerseWords(verseKey, requested));
    },
    load(db) {
      const words: [number, string, string][] = [];
      const allLines: DKLine[] = [];
      for (const page of fixture.pages) {
        page.locations.forEach((location, i) => {
          words.push([page.firstWordId + i, location, page.texts[db][i]]);
        });
        allLines.push(...pageLines(page));
      }
      this.loadData({rewayah: FIXTURE_DB_REWAYAH[db], words, lines: allLines});
    },
    loadData(data) {
      wordsById.clear();
      infoById.clear();
      verseWords.clear();
      lines.clear();
      for (const [wordId, location, text] of data.words) {
        const [surah, ayah, word] = location.split(':');
        const info: DKWordInfo = {
          text,
          verseKey: `${surah}:${ayah}`,
          wordPositionInVerse: parseInt(word, 10),
        };
        wordsById.set(wordId, text);
        infoById.set(wordId, info);
        const list = verseWords.get(info.verseKey);
        if (list) list.push(info);
        else verseWords.set(info.verseKey, [info]);
      }
      for (const list of verseWords.values()) {
        list.sort((a, b) => a.wordPositionInVerse - b.wordPositionInVerse);
      }
      for (const line of data.lines) {
        const pageList = lines.get(line.page_number);
        if (pageList) pageList.push(line);
        else lines.set(line.page_number, [line]);
      }
      rewayah = data.rewayah;
      version += 1;
    },
    bumpVersion() {
      version += 1;
    },
  };
}
