// AUTO-GENERATED by scripts/rewayah/gen-manifest.mjs. Do not edit by hand.
//
// sha256 of every Digital Khatt SQLite asset bundled by
// DigitalKhattDataService, keyed by the asset file basename. The app names
// each on-device copy `<base>.<first 8 hex chars>.db`, so changing an asset
// changes its on-device name and installed apps re-import it.
//
// Regenerate after changing any bundled DB:
//   node scripts/rewayah/gen-manifest.mjs
// services/mushaf/__tests__/rewayahDataManifest.test.ts fails when stale.

export const REWAYAH_DATA_MANIFEST: Readonly<Record<string, string>> = {
  'digital-khatt-15-lines.db':
    'bca39e611d305a6261e99c1b501a855f18861f9e58044825db0fd8d598e29728',
  'digital-khatt-v2.db':
    '071c0f43e30819b8b6427194c2f4c97ff05340da3808092c590967913b0382a6',
  'dk_words_bazzi.db':
    'b74167b16291c8aca09da1b24ca7c7608b27d9d7f7f79b77a92dca38ca022265',
  'dk_words_doori.db':
    'fd1633d4ccf65051d68a14475cc6fd39685561efb31f6f51fa63a360413b95b6',
  'dk_words_qaloon.db':
    '53c3f531e0053e12ef0d80c753ce36dd8c46d39faee420dfbaf66496047f19c1',
  'dk_words_qumbul.db':
    'b59463c3a1e79c93b99bf8494f9db0fd6d349cf9bed0364e8ba1304fc73a8fd2',
  'dk_words_shouba.db':
    'ba68656a3ed41a24ad74139d8bddbfb676992a83fda0f54fb7fc1b5fedcce205',
  'dk_words_soosi.db':
    '167b9270d4bd50f89178ca017c160c51661b1cf2854d313383ef12c3a7d9deb4',
  'dk_words_warsh.db':
    'd284add198b3f80cebb18842a03ebc2f1db5600ecccfc5e0e96ebae5284e4a84',
};

// md5 of the same assets: the platform file API reports md5, so the app
// checks each on-device copy against it once per session and re-imports
// a copy that was cut short (a copy can still open after that, with its
// last words silently altered).
export const REWAYAH_DATA_MD5: Readonly<Record<string, string>> = {
  'digital-khatt-15-lines.db': 'b52a3dd59f9cdf985b896a607c259953',
  'digital-khatt-v2.db': '9b4feda111e1daacf8e477feb9126ce2',
  'dk_words_bazzi.db': '545bacc4c9e4aff83c5c2e7b36ea3f32',
  'dk_words_doori.db': '91e04c3d80c84158c91cd36ff8a0148a',
  'dk_words_qaloon.db': '6297bacbf75ceee82bd07487df44ac72',
  'dk_words_qumbul.db': 'c8c6da2ad756b75610d8e5749cfb6aac',
  'dk_words_shouba.db': '5ad571c83b4a3fc6300bbaded7f9d562',
  'dk_words_soosi.db': '36d3487f77653c4df242234f841f1fb5',
  'dk_words_warsh.db': '11b82f49208e2a9a77718efb9ec0f8a3',
};
