/**
 * RewayahVerseMapService
 *
 * Translates verse keys between a rewayah's own verse numbering and the Hafs
 * verse keys that every bundled words DB, page layout, highlight renderer and
 * page-turn lookup is keyed by (contract C3, `<id>-versemap.json`).
 *
 * Each map is generated by the rewayah data pipeline from the final slot
 * assignment:
 *   - `verseCounts[surah]` is the rewayah's verse count,
 *   - `r2h["s:a"]` lists, in order, the Hafs verse keys whose slots hold the
 *     tokens of rewayah verse s:a,
 *   - `h2r["s:a"]` is the inverse (an empty list means the Hafs verse belongs
 *     to no rewayah verse, e.g. the Fatiha basmala in the Madani count),
 *   - entries equal to `[same key]` are omitted (identity).
 *
 * Hafs is the identity map by definition and needs no file. Rewayat without a
 * bundled map (the taxonomy-only ones) have no numbering information here:
 * every lookup returns an empty list / null so callers can refuse to guess.
 *
 * The maps are static bundled data (not derived from the words DBs at
 * runtime), so the parsed cache never needs invalidating on a rewayah switch.
 */

import {SURAHS} from '@/data/surahData';
import type {RewayahId} from '@/services/rewayah/RewayahIdentity';

export type VerseMapFileId =
  | 'warsh'
  | 'qaloon'
  | 'bazzi'
  | 'qumbul'
  | 'doori'
  | 'soosi'
  | 'shouba';

/** App RewayahId -> `<file id>-versemap.json` (contract C3). */
export const VERSE_MAP_FILE_IDS: Readonly<
  Partial<Record<RewayahId, VerseMapFileId>>
> = {
  warsh: 'warsh',
  qalun: 'qaloon',
  'al-bazzi': 'bazzi',
  qunbul: 'qumbul',
  'al-duri-abi-amr': 'doori',
  'al-susi': 'soosi',
  shubah: 'shouba',
};

export const VERSE_MAP_FORMAT = 1;

/** Raw JSON shape of a contract-C3 verse map. */
export interface RewayahVerseMapJson {
  __format: number;
  rewayah: string;
  verseCounts: Record<string, number>;
  r2h: Record<string, string[]>;
  h2r: Record<string, string[]>;
}

export type VerseMapLoader = () => unknown;

// Static require map: Metro only bundles literal require paths. Wrapped in
// thunks so a map is parsed the first time a reciter of that rewayah plays.
const DEFAULT_LOADERS: Readonly<Record<VerseMapFileId, VerseMapLoader>> = {
  warsh: () => require('@/data/mushaf/digitalkhatt/warsh-versemap.json'),
  qaloon: () => require('@/data/mushaf/digitalkhatt/qaloon-versemap.json'),
  bazzi: () => require('@/data/mushaf/digitalkhatt/bazzi-versemap.json'),
  qumbul: () => require('@/data/mushaf/digitalkhatt/qumbul-versemap.json'),
  doori: () => require('@/data/mushaf/digitalkhatt/doori-versemap.json'),
  soosi: () => require('@/data/mushaf/digitalkhatt/soosi-versemap.json'),
  shouba: () => require('@/data/mushaf/digitalkhatt/shouba-versemap.json'),
};

const TOTAL_SURAHS = 114;
const VERSE_KEY_RE = /^(\d{1,3}):(\d{1,3})$/;

export interface ParsedVerseKey {
  surah: number;
  ayah: number;
}

/** Parse "s:a" into numbers; null for anything that is not a verse key. */
export function parseVerseKey(key: string): ParsedVerseKey | null {
  const m = VERSE_KEY_RE.exec(key);
  if (!m) return null;
  const surah = Number(m[1]);
  const ayah = Number(m[2]);
  if (surah < 1 || surah > TOTAL_SURAHS || ayah < 1) return null;
  return {surah, ayah};
}

/** Hafs verse count of a surah (1-114), 0 for an invalid surah number. */
export function hafsVerseCount(surah: number): number {
  return SURAHS[surah - 1]?.verses_count ?? 0;
}

interface ParsedVerseMap {
  verseCounts: number[]; // index = surah number
  r2h: Map<string, readonly string[]>;
  h2r: Map<string, readonly string[]>;
  nonIdentitySurahs: Set<number>;
}

function isKeyList(value: unknown): value is string[] {
  return (
    Array.isArray(value) &&
    value.every(k => typeof k === 'string' && parseVerseKey(k) !== null)
  );
}

/**
 * Validate and index a contract-C3 verse map. Throws with a precise message on
 * any structural problem: a malformed map must never be used for Quran verse
 * navigation.
 */
export function parseVerseMap(
  raw: unknown,
  fileId: VerseMapFileId,
): ParsedVerseMap {
  if (typeof raw !== 'object' || raw === null) {
    throw new Error(`${fileId}: verse map is not an object`);
  }
  const doc = raw as Partial<RewayahVerseMapJson>;
  if (doc.__format !== VERSE_MAP_FORMAT) {
    throw new Error(
      `${fileId}: unsupported verse map format ${String(doc.__format)}`,
    );
  }
  if (doc.rewayah !== fileId) {
    throw new Error(
      `${fileId}: verse map declares rewayah "${String(doc.rewayah)}"`,
    );
  }
  const counts = doc.verseCounts;
  if (typeof counts !== 'object' || counts === null) {
    throw new Error(`${fileId}: verseCounts missing`);
  }
  const verseCounts: number[] = [0];
  for (let s = 1; s <= TOTAL_SURAHS; s++) {
    const n = (counts as Record<string, unknown>)[String(s)];
    if (typeof n !== 'number' || !Number.isInteger(n) || n < 1) {
      throw new Error(`${fileId}: verseCounts[${s}] is invalid`);
    }
    verseCounts.push(n);
  }

  const nonIdentitySurahs = new Set<number>();
  const index = (
    table: unknown,
    name: 'r2h' | 'h2r',
    keyCount: (surah: number) => number,
    valueCount: (surah: number) => number,
  ): Map<string, readonly string[]> => {
    if (typeof table !== 'object' || table === null || Array.isArray(table)) {
      throw new Error(`${fileId}: ${name} missing`);
    }
    const out = new Map<string, readonly string[]>();
    for (const [key, value] of Object.entries(table)) {
      const k = parseVerseKey(key);
      if (!k || k.ayah > keyCount(k.surah)) {
        throw new Error(`${fileId}: ${name} has an invalid key "${key}"`);
      }
      if (!isKeyList(value)) {
        throw new Error(`${fileId}: ${name}["${key}"] is not a key list`);
      }
      for (const v of value) {
        const p = parseVerseKey(v)!;
        if (p.surah !== k.surah || p.ayah > valueCount(p.surah)) {
          throw new Error(
            `${fileId}: ${name}["${key}"] points outside its surah ("${v}")`,
          );
        }
      }
      if (name === 'r2h' && value.length === 0) {
        throw new Error(`${fileId}: r2h["${key}"] is empty`);
      }
      out.set(key, Object.freeze(value.slice()));
      // An explicit [same key] entry is identity (the contract omits them,
      // but tolerate it without losing the surah's identity status).
      if (value.length !== 1 || value[0] !== key)
        nonIdentitySurahs.add(k.surah);
    }
    return out;
  };

  const r2h = index(
    doc.r2h,
    'r2h',
    s => verseCounts[s],
    s => hafsVerseCount(s),
  );
  const h2r = index(
    doc.h2r,
    'h2r',
    s => hafsVerseCount(s),
    s => verseCounts[s],
  );
  for (let s = 1; s <= TOTAL_SURAHS; s++) {
    if (verseCounts[s] !== hafsVerseCount(s)) nonIdentitySurahs.add(s);
  }
  return {verseCounts, r2h, h2r, nonIdentitySurahs};
}

export class RewayahVerseMapService {
  private readonly loaders: Readonly<Record<VerseMapFileId, VerseMapLoader>>;
  // null = the map failed to load / validate (logged once, then fail closed).
  private readonly cache = new Map<VerseMapFileId, ParsedVerseMap | null>();

  constructor(
    loaders: Readonly<Record<VerseMapFileId, VerseMapLoader>> = DEFAULT_LOADERS,
  ) {
    this.loaders = loaders;
  }

  /**
   * True when the rewayah should have numbering information: Hafs (identity)
   * or one of the rewayat with a bundled verse map.
   */
  expectsVerseMap(rewayah: RewayahId): boolean {
    return rewayah === 'hafs' || VERSE_MAP_FILE_IDS[rewayah] !== undefined;
  }

  /** True when numbering information is available (and valid) for the rewayah. */
  hasVerseMap(rewayah: RewayahId): boolean {
    if (rewayah === 'hafs') return true;
    return this.load(rewayah) !== null;
  }

  /** The rewayah's verse count for a surah, or null when unknown. */
  verseCount(rewayah: RewayahId, surah: number): number | null {
    if (surah < 1 || surah > TOTAL_SURAHS) return null;
    if (rewayah === 'hafs') return hafsVerseCount(surah);
    const map = this.load(rewayah);
    return map ? map.verseCounts[surah] : null;
  }

  /**
   * True when the rewayah numbers this surah exactly like Hafs (same count and
   * every verse maps to the same-numbered Hafs verse). Null when unknown.
   */
  isIdentitySurah(rewayah: RewayahId, surah: number): boolean | null {
    if (surah < 1 || surah > TOTAL_SURAHS) return null;
    if (rewayah === 'hafs') return true;
    const map = this.load(rewayah);
    return map ? !map.nonIdentitySurahs.has(surah) : null;
  }

  /**
   * Hafs verse keys holding rewayah verse `riwayahKey`, in reading order.
   * Empty when the key is not a verse of the rewayah or no map is available.
   */
  toHafsKeys(rewayah: RewayahId, riwayahKey: string): string[] {
    const k = parseVerseKey(riwayahKey);
    if (!k) return [];
    if (rewayah === 'hafs') {
      return k.ayah <= hafsVerseCount(k.surah) ? [riwayahKey] : [];
    }
    const map = this.load(rewayah);
    if (!map || k.ayah > map.verseCounts[k.surah]) return [];
    const mapped = map.r2h.get(riwayahKey);
    return mapped ? mapped.slice() : [riwayahKey];
  }

  /**
   * Rewayah verse keys covering Hafs verse `hafsKey`, in reading order. Empty
   * when the Hafs verse belongs to no rewayah verse (e.g. the Fatiha basmala
   * in the Madani count), the key is invalid, or no map is available.
   */
  toRiwayahKeys(rewayah: RewayahId, hafsKey: string): string[] {
    const k = parseVerseKey(hafsKey);
    if (!k || k.ayah > hafsVerseCount(k.surah)) return [];
    if (rewayah === 'hafs') return [hafsKey];
    const map = this.load(rewayah);
    if (!map) return [];
    const mapped = map.h2r.get(hafsKey);
    return mapped ? mapped.slice() : [hafsKey];
  }

  /** Drop parsed maps (tests). */
  clearCache(): void {
    this.cache.clear();
  }

  private load(rewayah: RewayahId): ParsedVerseMap | null {
    const fileId = VERSE_MAP_FILE_IDS[rewayah];
    if (!fileId) return null;
    if (this.cache.has(fileId)) return this.cache.get(fileId) ?? null;
    let parsed: ParsedVerseMap | null = null;
    try {
      parsed = parseVerseMap(this.loaders[fileId](), fileId);
    } catch (error) {
      console.error(
        `[RewayahVerseMap] ${fileId}-versemap.json rejected; follow-along stays disabled for this rewayah:`,
        error,
      );
    }
    this.cache.set(fileId, parsed);
    return parsed;
  }
}

export const rewayahVerseMapService = new RewayahVerseMapService();
