// AUTO-GENERATED by scripts/rewayah/gen-manifest.mjs. Do not edit by hand.
//
// sha256 of every Digital Khatt SQLite asset bundled by
// DigitalKhattDataService, keyed by the asset file basename. The app names
// each on-device copy `<base>.<first 8 hex chars>.db`, so changing an asset
// changes its on-device name and installed apps re-import it.
//
// Regenerate after changing any bundled DB:
//   node scripts/rewayah/gen-manifest.mjs
// services/mushaf/__tests__/rewayahDataManifest.test.ts fails when stale.

export const REWAYAH_DATA_MANIFEST: Readonly<Record<string, string>> = {
  'digital-khatt-15-lines.db':
    'bca39e611d305a6261e99c1b501a855f18861f9e58044825db0fd8d598e29728',
  'digital-khatt-v2.db':
    '071c0f43e30819b8b6427194c2f4c97ff05340da3808092c590967913b0382a6',
  'dk_words_bazzi.db':
    '8bfc31bfba485df98cfd05e5eafcd18566a6d9b8a89714c44646d1e39c1ac588',
  'dk_words_doori.db':
    'd000de8795fa3a71b5a04a6c9c9404dd802f4383dfd9f3dc8de8ab229c1bd568',
  'dk_words_qaloon.db':
    '90b47c3b52af34f954e9e22c35862b6b20a050c19d6bf0d3a995ac6d9ffd63ed',
  'dk_words_qumbul.db':
    'dbb499b13b03c584d4933796dae792381d723310244b79cb09990fd32c18df14',
  'dk_words_shouba.db':
    'cae17a91e8fdbaf413d8a20177ab274090ab99be73481b596dc3bb67bd93e6d6',
  'dk_words_soosi.db':
    'df24adc02fe5c80931dfde20f02d800a054d5f87d9fe0f1179a96ae623ffd71d',
  'dk_words_warsh.db':
    '702885469af3a1006027e86ade7692018a00914be6993a88f95d9ab4eae65d27',
};
